### ISSUE TITLE
Make different versions of the repository for pre-alpha v7 and bleeding edge v7

### ISSUE THREAD

**Issue by PurpleSushi22** [Evo04Taser/Super-Cheat#1]

**Comment by Evo04Taser** [comment]
Sorry, I can't do it, the reason is:

When the pre-alpha V7 is officially released, then the bleeding edge V7 will become pre-alpha, and so introduces a new bleeding edge build, which will might change Mindustry logic, and so I will start this mod all over.

**Comment by PurpleSushi22** [comment]
I think I may have done some things wrong on my part. Just make a seperate branch for the "erekir phase of v7".
That way, the current bleeding edge builds get seperated from the future bleeding edge builds, when v7 eventually releases.

**Comment by PurpleSushi22** [comment]
Obsolete, since v7 alpha is already out.
