### ISSUE TITLE
Superwalls spawning in campaign 

### ISSUE THREAD

**Issue by MindOfBalls** [Evo04Taser/Super-Cheat#2]
First of all, thank you for the great mod.

Serpulo enemy bases (that aren't named) are spawning with superwalls.

I use this mod to have fun attacking the campaign bases but numbered bases spawn with superwalls destroy all attacks and units besides using the super turret to destroy it.

Not sure if this is intended but it makes attacking not fun :(

Also I'm on mobile and haven't dove into the other planets content yet

**Comment by Evo04Taser** [comment]
Im sorry, but that has something to do with the source code of Mindustry, so i can't fix it

Edit: I'm trying to fix it
